### ISSUE TITLE
Support for dot at the end of currency name

### ISSUE THREAD

**Issue by thezed** [caiogondim/parse-price.js#3]
```
parsePrice('1&nbsp;490,00 руб.')
=> 149000
```
Should be 1490.00

**Comment by caiogondim** [comment]
`1&nbsp;490,00 руб` gives you the right result.

Is `1&nbsp;490,00 руб.` a valid/common price display in Russia?
Should we support that or `1&nbsp;490,00 руб` is enough?

**Comment by thezed** [comment]
Yes, 'р.' and 'руб.' with trailing dot are valid and they are the most common shortcut of 'рубль'
It is used by major web retailers, e.g. on ASOS [(link)](http://www.asos.com/ru/asos/uzkij-kozhanyj-korichnevyj-remen-s-otdelkoj-asos/prd/8857844?clr=коричневый&SearchQuery=&cid=6474&gridcolumn=1&gridrow=1&gridsize=4&pge=1&pgesize=72&totalstyles=208)

**Comment by caiogondim** [comment]
Done on 7c02105

**Comment by caiogondim** [comment]
Published a new release with your use case
